nelmio_api_doc:
    documentation:
        info:
            title: Geonames
            description: Geonames API Documentation
            version: 1.0.0
        tags:
            - name: 'Geonames Status'
              description: Geonames Status endpoint
            - name: 'Geonames GeoJson'
              description: Geonames GeoJson endpoints
            - name: 'Geonames API'
              description: Geonames API endpoints
            - name: 'Geonames Homepage'
              description: Geonames Homepage
            - name: 'Geonames Countries Barycenters'
              description: Geonames Barycenters endpoints
            - name: 'Geonames Countries Level'
              description: Geonames Countries Level endpoints
            - name: 'Geonames Countries Locales'
              description: Geonames Countries Locales endpoints
            - name: 'Geonames Search'
              description: Geonames Search endpoint
            - name: 'Geonames Translations'
              description: Geonames Translations endpoints
    areas: # to filter documented areas
        path_patterns:
           # - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/(?!api$)