when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        register_error_listener: false
        register_error_handler: false
        options:
            integrations:
                - 'Sentry\Integration\IgnoreErrorsIntegration'

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface

services:
    Sentry\Integration\IgnoreErrorsIntegration:
        arguments:
            $options:
                ignore_exceptions:
                    - ApiPlatform\Exception\ItemNotFoundException
                    - App\Exception\ClientNotFoundException
                    - Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException
                    - Symfony\Component\HttpKernel\Exception\HttpException
                    - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
                    - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                    - Symfony\Component\Serializer\Exception\NotNormalizableValueException
