name: GTR Core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_GH_TOKEN }}
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
        env:
          NPM_TOKEN: ${{ secrets.CI_GH_TOKEN }}
      - name: 'Install dependencies'
        run: yarn install --frozen-lockfile
        env:
          NPM_TOKEN: ${{ secrets.CI_GH_TOKEN }}
      - name: 'Release'
        run: |
          yarn gh-action-gtr-semantic-release
        env:
          NODE_ENV: test
          SEMVER_RELEASE_TYPE: PHP_SCALINGO_SH
          NPM_TOKEN: ${{ secrets.CI_GH_TOKEN }}
          ACTION_GH_TOKEN: ${{ secrets.CI_GH_TOKEN }}
          GH_TOKEN: ${{ secrets.CI_GH_TOKEN }}
          PUBLISH_SLACK_CHANNEL: 'geonames'
          PUBLISH_SLACK_ICON: ':saxophone:'
      - name: Rebase dev branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: git fetch && git checkout dev && git rebase origin/main && git push origin dev --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GH_TOKEN }}
  # https://github.community/t5/GitHub-Actions/Workflow-is-failing-if-no-job-can-be-ran-due-to-condition/m-p/38186#M3250
  always_job:
    name: Aways run job
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Always run
        run: echo "This job is used to prevent the workflow to fail when all other jobs are skipped."
